Add deploy frontends key value
RedHatInsights/bonfire-tekton pull request #40
Opened 2024-06-12 11:47 UTC by akhil-jha

2024-06-12 12:37 UTC, akhil-jha commented
@bsquizz @ernesgonzalez33  Any idea why the pipeline is failing?

2024-06-12 16:08 UTC, ernesgonzalez33 requested changes

2024-06-12 16:08 UTC, ernesgonzalez33 commented on tasks/deploy.yaml
> +      type: boolean
Type boolean doesn't exist in Tekton, these are the correct types: https://tekton.dev/docs/pipelines/tasks/#parameter-type

2024-06-12 16:09 UTC, ernesgonzalez33 commented
> @bsquizz @ernesgonzalez33 Any idea why the pipeline is failing?

Added a review

2024-06-12 16:23 UTC, ernesgonzalez33 requested changes
If you want to be able to set up the parameter in the pipeline as well, you will need to add it to the basic pipeline and then pass it to the task

2024-06-13 16:21 UTC, akhil-jha commented
> If you want to be able to set up the parameter in the pipeline as well, you will need to add it to the basic pipeline and then pass it to the task

@ernesgonzalez33  I've added changes. 
I don't have access to rhtap-migration-tenant, can't debug the failure for run-iqe-cji

2024-06-18 12:35 UTC, ernesgonzalez33 commented
@akhil-jha sorry I haven't been able to debug this issue and the Konflux UI has an outage today. I'll make sure to check it tomorrow

2024-06-19 07:50 UTC, akhil-jha commented
> @akhil-jha sorry I haven't been able to debug this issue and the Konflux UI has an outage today. I'll make sure to check it tomorrow

Sure! :)

2024-06-19 13:30 UTC, ernesgonzalez33 commented
/retest

2024-06-19 13:43 UTC, ernesgonzalez33 approved these changes

2024-06-19 13:44 UTC, merged